class_name NetworkErrorCodes
extends RefCounted

const ROOM_CREATE_FAILED := "ROOM_CREATE_FAILED"
const ROOM_JOIN_FAILED := "ROOM_JOIN_FAILED"
const ROOM_START_FORBIDDEN := "ROOM_START_FORBIDDEN"
const ROOM_MEMBER_NOT_READY := "ROOM_MEMBER_NOT_READY"
const ROOM_SELECTION_INVALID := "ROOM_SELECTION_INVALID"
const ROOM_MEMBER_PROFILE_INVALID := "ROOM_MEMBER_PROFILE_INVALID"

const MATCH_CONFIG_BUILD_FAILED := "MATCH_CONFIG_BUILD_FAILED"
const MATCH_CONFIG_VALIDATE_FAILED := "MATCH_CONFIG_VALIDATE_FAILED"
const MATCH_START_SCENE_LOAD_FAILED := "MATCH_START_SCENE_LOAD_FAILED"
const MATCH_START_RUNTIME_BOOTSTRAP_FAILED := "MATCH_START_RUNTIME_BOOTSTRAP_FAILED"

const BATTLE_RUNTIME_ERROR := "BATTLE_RUNTIME_ERROR"
const BATTLE_TICK_STALLED := "BATTLE_TICK_STALLED"
const BATTLE_DISCONNECTED := "BATTLE_DISCONNECTED"
const BATTLE_HOST_LEFT := "BATTLE_HOST_LEFT"

const RETURN_ROOM_FAILED := "RETURN_ROOM_FAILED"
const SESSION_RECOVERY_FAILED := "SESSION_RECOVERY_FAILED"
