class_name TransportMessageTypes
extends RefCounted

const JOIN_BATTLE_REQUEST := "JOIN_BATTLE_REQUEST"
const JOIN_BATTLE_ACCEPTED := "JOIN_BATTLE_ACCEPTED"
const JOIN_BATTLE_REJECTED := "JOIN_BATTLE_REJECTED"
const MATCH_START := "MATCH_START"
const INPUT_FRAME := "INPUT_FRAME"
const INPUT_ACK := "INPUT_ACK"
const STATE_SUMMARY := "STATE_SUMMARY"
const CHECKPOINT := "CHECKPOINT"
const AUTHORITATIVE_SNAPSHOT := "AUTHORITATIVE_SNAPSHOT"
const MATCH_FINISHED := "MATCH_FINISHED"
const PING := "PING"
const PONG := "PONG"
