import os
from typing import Any, Callable, NoReturn, cast

from SCons.Script import (  # pyright: ignore[reportMissingTypeStubs]
    ARGUMENTS as SCONS_ARGUMENTS,
    Default as SCONS_DEFAULT,
    Environment as SCONS_ENVIRONMENT,
    Exit as SCONS_EXIT,
)


PROJECT_DIR = os.getcwd()
SRC_DIR = os.path.join(PROJECT_DIR, "src")
BIN_DIR = os.path.join(PROJECT_DIR, "bin")
GODOT_CPP_DIR = os.path.join(PROJECT_DIR, "third_party", "godot-cpp")

ARGUMENTS = cast(dict[str, str], SCONS_ARGUMENTS)
Default = cast(Callable[[Any], Any], SCONS_DEFAULT)
Environment = cast(Callable[[], Any], SCONS_ENVIRONMENT)
Exit = cast(Callable[[int], NoReturn], SCONS_EXIT)


def fail(message: str) -> NoReturn:
    print("qqt_native SConstruct error: %s" % message)
    Exit(1)
    raise SystemExit(1)


if not os.path.isdir(GODOT_CPP_DIR):
    fail("missing godot-cpp dependency at addons/qqt_native/third_party/godot-cpp")


platform: str = ARGUMENTS.get("platform", "windows")
target: str = ARGUMENTS.get("target", "template_debug")
arch: str = ARGUMENTS.get("arch", "x86_64")
dev_build: str = ARGUMENTS.get("dev_build", "no")

if platform not in ["windows", "linux"]:
    fail(
        "unsupported platform: %s. Supported Current qqt_native build matrix entries are windows and linux; "
        % platform
        + "add matching godot-cpp static libraries and platform-specific output wiring before enabling another platform."
    )

if target not in ["template_debug", "template_release"]:
    fail("unsupported target: %s" % target)

if arch != "x86_64":
    fail("unsupported arch: %s" % arch)


env: Any = Environment()
env.Append(CPPDEFINES=["TYPED_METHOD_BIND"])
env.Append(CPPPATH=[
    SRC_DIR,
    os.path.join(GODOT_CPP_DIR, "include"),
    os.path.join(GODOT_CPP_DIR, "gen", "include"),
])

if platform == "windows":
    env.Append(CXXFLAGS=["/std:c++17", "/EHsc"])
    shared_suffix = ".dll"
    godot_cpp_suffix = ".lib"
elif platform == "linux":
    env.Append(CXXFLAGS=["-std=c++17", "-fPIC"])
    env.Append(LINKFLAGS=["-shared"])
    shared_suffix = ".so"
    godot_cpp_suffix = ".a"
else:
    fail("unsupported platform: %s" % platform)

if target == "template_debug":
    env.Append(CPPDEFINES=["DEBUG_ENABLED"])

variant_dir = os.path.join(BIN_DIR, "obj", platform, target, arch)
godot_cpp_lib = os.path.join(
    GODOT_CPP_DIR,
    "bin",
    "libgodot-cpp.%s.%s.%s%s%s" % (
        platform,
        target,
        arch,
        ".dev" if dev_build == "yes" else "",
        godot_cpp_suffix,
    ),
)

if not os.path.isfile(godot_cpp_lib):
    fail("missing godot-cpp static library: %s" % godot_cpp_lib)

sources = [
    os.path.join(SRC_DIR, "register_types.cpp"),
    os.path.join(SRC_DIR, "codec", "native_packed_state_codec.cpp"),
    os.path.join(SRC_DIR, "checksum", "native_checksum_builder.cpp"),
    os.path.join(SRC_DIR, "snapshot", "native_snapshot_ring.cpp"),
    os.path.join(SRC_DIR, "movement", "native_movement_kernel.cpp"),
    os.path.join(SRC_DIR, "explosion", "native_explosion_kernel.cpp"),
    os.path.join(SRC_DIR, "sync", "native_authority_batch_coalescer.cpp"),
    os.path.join(SRC_DIR, "sync", "native_input_buffer.cpp"),
    os.path.join(SRC_DIR, "sync", "native_snapshot_diff.cpp"),
    os.path.join(SRC_DIR, "sync", "native_rollback_planner.cpp"),
    os.path.join(SRC_DIR, "sync", "native_battle_message_codec.cpp"),
]

bin_name = "qqt_native.%s.%s.%s" % (platform, target, arch)
target_path = os.path.join(BIN_DIR, "%s%s" % (bin_name, shared_suffix))

library = env.SharedLibrary(
    target=target_path,
    source=sources,
    LIBS=[env.File(godot_cpp_lib)],
)

Default(library)

