import os

from SCons.Script import ARGUMENTS, Environment, Exit


PROJECT_DIR = os.getcwd()
SRC_DIR = os.path.join(PROJECT_DIR, "src")
BIN_DIR = os.path.join(PROJECT_DIR, "bin")
GODOT_CPP_DIR = os.path.join(PROJECT_DIR, "third_party", "godot-cpp")


def fail(message):
    print("qqt_native SConstruct error: %s" % message)
    Exit(1)


if not os.path.isdir(GODOT_CPP_DIR):
    fail("missing godot-cpp dependency at addons/qqt_native/third_party/godot-cpp")


platform = ARGUMENTS.get("platform", "windows")
target = ARGUMENTS.get("target", "template_debug")
arch = ARGUMENTS.get("arch", "x86_64")
dev_build = ARGUMENTS.get("dev_build", "no")
debug_symbols = ARGUMENTS.get("debug_symbols", "yes")

if platform not in ["windows", "linux"]:
    fail(
        "unsupported platform: %s. Supported Phase31 qqt_native build matrix entries are windows and linux; "
        "add matching godot-cpp static libraries and platform-specific output wiring before enabling another platform."
        % platform
    )

if target not in ["template_debug", "template_release"]:
    fail("unsupported target: %s" % target)

if arch != "x86_64":
    fail("unsupported arch: %s" % arch)


env = Environment()
env.Append(CPPDEFINES=["TYPED_METHOD_BIND"])
env.Append(CPPPATH=[
    SRC_DIR,
    os.path.join(GODOT_CPP_DIR, "include"),
    os.path.join(GODOT_CPP_DIR, "gen", "include"),
])

if platform == "windows":
    env.Append(CXXFLAGS=["/std:c++17", "/EHsc"])
    shared_suffix = ".dll"
    godot_cpp_suffix = ".lib"
elif platform == "linux":
    env.Append(CXXFLAGS=["-std=c++17", "-fPIC"])
    env.Append(LINKFLAGS=["-shared"])
    shared_suffix = ".so"
    godot_cpp_suffix = ".a"

if target == "template_debug":
    env.Append(CPPDEFINES=["DEBUG_ENABLED"])

variant_dir = os.path.join(BIN_DIR, "obj", platform, target, arch)
godot_cpp_lib = os.path.join(
    GODOT_CPP_DIR,
    "bin",
    "libgodot-cpp.%s.%s.%s%s%s" % (
        platform,
        target,
        arch,
        ".dev" if dev_build == "yes" else "",
        godot_cpp_suffix,
    ),
)

if not os.path.isfile(godot_cpp_lib):
    fail("missing godot-cpp static library: %s" % godot_cpp_lib)

sources = [
    os.path.join(SRC_DIR, "register_types.cpp"),
    os.path.join(SRC_DIR, "codec", "native_packed_state_codec.cpp"),
    os.path.join(SRC_DIR, "checksum", "native_checksum_builder.cpp"),
    os.path.join(SRC_DIR, "snapshot", "native_snapshot_ring.cpp"),
    os.path.join(SRC_DIR, "movement", "native_movement_kernel.cpp"),
    os.path.join(SRC_DIR, "explosion", "native_explosion_kernel.cpp"),
]

bin_name = "qqt_native.%s.%s.%s" % (platform, target, arch)
target_path = os.path.join(BIN_DIR, "%s%s" % (bin_name, shared_suffix))

library = env.SharedLibrary(
    target=target_path,
    source=sources,
    LIBS=[godot_cpp_lib],
)

Default(library)
