class_name BattleWireBudgetContract
extends RefCounted

const WIRE_VERSION := 2
const UNRELIABLE_SOFT_LIMIT_BYTES := 1200
const INPUT_BATCH_TARGET_BYTES_2P := 600
const INPUT_BATCH_TARGET_BYTES_4P := 900
const STATE_SUMMARY_TARGET_BYTES_2P := 900
const STATE_SUMMARY_TARGET_BYTES_4P := 1100
const CHECKPOINT_RELIABLE_TARGET_BYTES := 8192
const INPUT_BATCH_WARN_BYTES := 900
const STATE_SUMMARY_WARN_BYTES := 1100
const MAX_INPUT_FRAMES_PER_BATCH := 16
const EDGE_ACTION_REDUNDANCY_TICKS := 3
const ACK_SAFETY_MARGIN_TICKS := 2
