name: game_service_test

services:
  postgres_test:
    # latest inspected on 2026-04-13 -> app version 18.3.0
    image: bitnami/postgresql@sha256:155a5ff04d5059d8076a85dca404d8a3bc2d765db0fea1afd25ae68e9ac38903
    container_name: qqtang_game_pg_test
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: qqtang_game_test
      POSTGRESQL_PASSWORD: qqtang_game_test_pass
      POSTGRESQL_DATABASE: qqtang_game_test
    ports:
      - "54332:5432"
    volumes:
      - qqtang_game_pgtestdata:/bitnami/postgresql

volumes:
  qqtang_game_pgtestdata:
