from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]


class FrontSceneContractTests(unittest.TestCase):
    def test_shop_and_inventory_scenes_are_registered(self) -> None:
        scene_flow = (ROOT / "app" / "flow" / "scene_flow_controller.gd").read_text(encoding="utf-8")
        self.assertIn('SHOP_SCENE_PATH: String = "res://scenes/front/shop_scene.tscn"', scene_flow)
        self.assertIn('INVENTORY_SCENE_PATH: String = "res://scenes/front/inventory_scene.tscn"', scene_flow)
        self.assertIn("func change_to_shop_scene()", scene_flow)
        self.assertIn("func change_to_inventory_scene()", scene_flow)

    def test_front_flow_has_shop_and_inventory_states(self) -> None:
        front_flow = (ROOT / "app" / "flow" / "front_flow_controller.gd").read_text(encoding="utf-8")
        self.assertIn("SHOP,", front_flow)
        self.assertIn("INVENTORY,", front_flow)
        self.assertIn("func enter_shop()", front_flow)
        self.assertIn("func enter_inventory()", front_flow)

    def test_lobby_and_room_bind_front_state(self) -> None:
        lobby_state = (ROOT / "app" / "front" / "lobby" / "lobby_view_state.gd").read_text(encoding="utf-8")
        lobby_controller = (ROOT / "scenes" / "front" / "lobby_scene_controller.gd").read_text(encoding="utf-8")
        room_binder = (ROOT / "scenes" / "front" / "room_scene_view_binder.gd").read_text(encoding="utf-8")
        self.assertIn("wallet_summary_text", lobby_state)
        self.assertIn("inventory_status_text", lobby_state)
        self.assertIn("shop_status_text", lobby_state)
        self.assertIn("_ensure_summary_rows", lobby_controller)
        self.assertIn('profile.get("title_id")', room_binder)
        self.assertIn('profile.get("avatar_id")', room_binder)

    def test_lobby_scene_is_formalized(self) -> None:
        lobby_controller = (ROOT / "scenes" / "front" / "lobby_scene_controller.gd").read_text(encoding="utf-8")
        self.assertIn("_apply_formal_lobby_layout", lobby_controller)
        self.assertIn("_build_reference_lobby_layout", lobby_controller)
        self.assertIn("ReferenceLobbyLayout", lobby_controller)
        self.assertIn("_refresh_reference_custom_room_list", lobby_controller)
        self.assertIn("_create_custom_room_list_row", lobby_controller)
        self.assertIn("_create_custom_room_placeholder", lobby_controller)
        self.assertIn("_change_custom_room_page", lobby_controller)
        self.assertIn("CUSTOM_ROOM_PAGE_SIZE := 8", lobby_controller)
        self.assertIn("_join_custom_room_by_id", lobby_controller)
        self.assertIn("_show_profile_popup", lobby_controller)
        self.assertIn("_on_create_room_menu_pressed", lobby_controller)
        self.assertIn("_auto_connect_room_directory", lobby_controller)
        self.assertIn("_connect_or_refresh_room_directory", lobby_controller)
        self.assertIn("_reparent_account_card_children", lobby_controller)
        self.assertIn("_apply_lobby_asset_ids", lobby_controller)
        self.assertIn('set_meta("ui_asset_id"', lobby_controller)
        self.assertIn("ui.lobby.bg.main", lobby_controller)
        self.assertIn("ui.lobby.button.shop.normal", lobby_controller)
        self.assertIn('"个人资料"', lobby_controller)
        self.assertIn('"经典模式"', lobby_controller)
        self.assertIn('"探险模式"', lobby_controller)
        self.assertIn('"大厅玩家"', lobby_controller)
        self.assertIn('"大厅聊天"', lobby_controller)
        self.assertIn('"道具商城"', lobby_controller)
        self.assertIn('"新手练习"', lobby_controller)
        self.assertIn('"自定义房间"', lobby_controller)
        self.assertIn('"匹配房间"', lobby_controller)
        self.assertIn('"排位房间"', lobby_controller)
        self.assertNotIn('"家具商城"', lobby_controller)
        self.assertNotIn('"聊天房间"', lobby_controller)
        self.assertNotIn('"Public"', lobby_controller)
        self.assertNotIn('"Private"', lobby_controller)

    def test_loading_uses_task_progress_aggregator(self) -> None:
        loading_use_case = (ROOT / "app" / "front" / "loading" / "loading_use_case.gd").read_text(encoding="utf-8")
        aggregator = (ROOT / "app" / "front" / "loading" / "loading_progress_aggregator.gd").read_text(encoding="utf-8")
        self.assertIn("AsyncLoadingPlanScript", loading_use_case)
        self.assertIn("_progress_aggregator.aggregate", loading_use_case)
        self.assertIn("weighted_progress", aggregator)
        self.assertNotIn("progress +=", loading_use_case)

    def test_battle_hud_binds_resource_ids_without_core_paths(self) -> None:
        hud_controller = (ROOT / "presentation" / "battle" / "hud" / "battle_hud_controller.gd").read_text(encoding="utf-8")
        hud_binder = (ROOT / "presentation" / "battle" / "hud" / "battle_hud_resource_binder.gd").read_text(encoding="utf-8")
        self.assertIn("BattleHudResourceBinderScript", hud_controller)
        self.assertIn("_bind_hud_resource_ids", hud_controller)
        self.assertIn("_apply_formal_hud_layout", hud_controller)
        self.assertIn("_ensure_reference_item_bar", hud_controller)
        self.assertIn("ReferenceItemBar", hud_controller)
        self.assertIn("hud_asset_bindings", hud_controller)
        self.assertIn('set_meta("ui_asset_id"', hud_binder)
        self.assertNotIn("res://external/assets/ui/battle", hud_controller)

    def test_room_loading_shop_inventory_are_formalized(self) -> None:
        room_controller = (ROOT / "scenes" / "front" / "room" / "room_scene_controller_impl.gd").read_text(encoding="utf-8")
        room_layout_builder = (ROOT / "scenes" / "front" / "room" / "room_formal_layout_builder.gd").read_text(encoding="utf-8")
        room_loadout_presenter = (ROOT / "scenes" / "front" / "room" / "room_formal_loadout_presenter.gd").read_text(encoding="utf-8")
        room_slot_presenter = (ROOT / "scenes" / "front" / "room" / "room_formal_slot_presenter.gd").read_text(encoding="utf-8")
        room_popup_controller = (ROOT / "scenes" / "front" / "room" / "room_formal_popup_controller.gd").read_text(encoding="utf-8")
        room_theme_applier = (ROOT / "scenes" / "front" / "room" / "room_formal_theme_applier.gd").read_text(encoding="utf-8")
        room_formal_sources = "\n".join([room_controller, room_layout_builder, room_loadout_presenter, room_slot_presenter, room_popup_controller, room_theme_applier])
        loading_controller = (ROOT / "scenes" / "front" / "loading_scene_controller.gd").read_text(encoding="utf-8")
        shop_controller = (ROOT / "scenes" / "front" / "shop_scene_controller.gd").read_text(encoding="utf-8")
        inventory_controller = (ROOT / "scenes" / "front" / "inventory_scene_controller.gd").read_text(encoding="utf-8")
        self.assertIn("_apply_formal_room_layout", room_controller)
        self.assertIn("_build_reference_room_layout", room_formal_sources)
        self.assertIn("ReferenceRoomLayout", room_layout_builder)
        self.assertIn("FORMAL_ROOM_SLOT_COUNT := 8", room_controller)
        self.assertIn("_formal_slot_grid", room_controller)
        self.assertIn("_refresh_reference_room_panels", room_controller)
        self.assertIn("_refresh_formal_room_slots", room_formal_sources)
        self.assertIn("_toggle_formal_slot", room_formal_sources)
        self.assertIn("_formal_closed_slots", room_formal_sources)
        self.assertIn("_show_formal_member_profile", room_formal_sources)
        self.assertIn("_change_formal_character_page", room_formal_sources)
        self.assertIn("_on_gateway_room_snapshot_received", room_controller)
        self.assertIn("_force_refresh_current_room_view", room_controller)
        self.assertIn("_apply_room_small_button_style", room_formal_sources)
        self.assertIn("_apply_room_square_button_style", room_formal_sources)
        self.assertIn("_color_for_character_id", room_formal_sources)
        self.assertIn("RoomCharacterPreviewScene", room_formal_sources)
        self.assertIn("_add_formal_character_preview", room_formal_sources)
        self.assertIn("_on_formal_choose_mode_pressed", room_formal_sources)
        self.assertIn("_on_formal_room_property_pressed", room_formal_sources)
        self.assertIn("_on_formal_choose_map_pressed", room_formal_sources)
        self.assertIn("_select_formal_custom_map", room_formal_sources)
        self.assertIn("_select_formal_match_mode", room_formal_sources)
        self.assertIn('"选择模式"', room_formal_sources)
        self.assertIn('"竞技模式"', room_formal_sources)
        self.assertIn('"探险模式"', room_formal_sources)
        self.assertIn('"房间属性"', room_formal_sources)
        self.assertIn('"选择地图"', room_formal_sources)
        self.assertIn('"房间聊天"', room_formal_sources)
        self.assertIn('"角色选择"', room_formal_sources)
        self.assertIn('"队伍选择"', room_formal_sources)
        self.assertIn('"离开房间"', room_formal_sources)
        self.assertNotIn('"经典模式"', room_controller)
        self.assertNotIn('"积分模式"', room_controller)
        self.assertNotIn('"我的背包"', room_controller)
        self.assertIn("_move_node_to", room_formal_sources)
        self.assertIn("ui.room.bg.main", room_formal_sources)
        self.assertIn("ui.room.button.ready.normal", room_formal_sources)
        self.assertIn("_ensure_loading_background", loading_controller)
        self.assertIn("_build_reference_loading_layout", loading_controller)
        self.assertIn("_update_reference_progress", loading_controller)
        self.assertIn("ReferenceLoadingLayout", loading_controller)
        self.assertIn("ui.loading.bg.main", loading_controller)
        self.assertIn("ui.loading.panel.task", loading_controller)
        self.assertIn("ui.shop.bg.main", shop_controller)
        self.assertIn("ui.shop.panel.detail", shop_controller)
        self.assertIn("max_columns = 3", shop_controller)
        self.assertIn("ui.shop.tab.characters.normal", shop_controller)
        self.assertIn("ui.inventory.bg.main", inventory_controller)
        self.assertIn("ui.inventory.panel.grid", inventory_controller)
        self.assertIn("max_columns = 4", inventory_controller)
        self.assertIn("ui.inventory.tab.characters.normal", inventory_controller)

    def test_scene_files_reference_controllers(self) -> None:
        shop_scene = (ROOT / "scenes" / "front" / "shop_scene.tscn").read_text(encoding="utf-8")
        inventory_scene = (ROOT / "scenes" / "front" / "inventory_scene.tscn").read_text(encoding="utf-8")
        self.assertIn("res://scenes/front/shop_scene_controller.gd", shop_scene)
        self.assertIn("res://scenes/front/inventory_scene_controller.gd", inventory_scene)

    def test_login_scene_is_formalized(self) -> None:
        login_controller = (ROOT / "scenes" / "front" / "login_scene_controller.gd").read_text(encoding="utf-8")
        self.assertIn("_apply_formal_login_layout", login_controller)
        self.assertIn('set_meta("ui_asset_id"', login_controller)
        self.assertIn("ui.login.bg.main", login_controller)
        self.assertIn("ui.login.panel.auth", login_controller)
        self.assertIn("ui.login.button.login.normal", login_controller)
        self.assertNotIn("Register opens the browser registration page", login_controller)


if __name__ == "__main__":
    unittest.main()


